# Generated by Django 4.1.5 on 2023-01-27 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('producto', '0001_initial'),
        ('carrito_compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cliente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_orden', to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='cliente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='producto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='producto.producto'),
        ),
    ]
