# Generated by Django 4.1.5 on 2023-01-26 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_alter_producto_precio'),
        ('carrito_compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='producto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='producto.producto'),
        ),
    ]
