# Generated by Django 4.1.5 on 2023-01-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_compra', '0004_alter_carrito_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
    ]
