# Generated by Django 4.1.5 on 2023-01-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_compra', '0005_carrito_is_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
