# Generated by Django 4.1.5 on 2023-01-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_compra', '0007_carrito_subtotal_carrito_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
    ]
