# Generated by Django 4.1.5 on 2023-01-26 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_carrito'),
        ('carrito_compra', '0009_alter_carrito_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='total',
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('descuento_total', models.FloatField(default=0)),
                ('carrito', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrito_orden', to='carrito_compra.carrito')),
                ('cliente', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_orden', to='cliente.cliente')),
            ],
            options={
                'db_table': 'api_orden',
            },
        ),
    ]
