# Generated by Django 4.1.5 on 2023-01-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_compra', '0010_remove_carrito_total_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cantidad_total',
            field=models.IntegerField(default=0),
        ),
    ]
